baseurl = "https://colinfinck.github.io/"
title = "ReactOS Website"
theme = "reactos"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "News"
    weight = 1
    [[menu.main]]
        parent = "News"
        name = "All News"
        url  = "/news/"
        weight = 101
    [[menu.main]]
        parent = "News"
        name = "Project News"
        url  = "/project-news/"
        weight = 102
    [[menu.main]]
        parent = "News"
        name = "Blog Posts"
        url  = "/blogs/"
        weight = 103

[[menu.main]]
    name = "Community"
    weight = 2
    [[menu.main]]
        parent = "Community"
        name = "Chat"
        url  = "https://chat.reactos.org"
        weight = 201
    [[menu.main]]
        parent = "Community"
        name = "Forum"
        url  = "/forum"
        weight = 202
    [[menu.main]]
        parent = "Community"
        name = "Shop"
        url  = "https://reactos.spreadshirt.net"
        weight = 203

[[menu.main]]
    name = "Development"
    weight = 3
    [[menu.main]]
        parent = "Development"
        name = "Jira"
        url  = "https://jira.reactos.org"
        weight = 301
    [[menu.main]]
        parent = "Development"
        name = "ReactOS Builds"
        url = "/getbuilds"
        weight = 302
    [[menu.main]]
        parent = "Development"
        name = "ReactOS on GitHub"
        url = "https://github.com/reactos"
        weight = 303
    [[menu.main]]
        parent = "Development"
        name = "Report a Bug"
        url  = "https://reactos.org/wiki/File_Bugs"
        weight = 304
    [[menu.main]]
        parent = "Development"
        name = "Testman"
        url  = "/testman"
        weight = 305
    [[menu.main]]
        parent = "Development"
        name = "Wiki"
        url  = "/wiki"
        weight = 306

[[menu.main]]
    name = "Donate"
    url  = "/donate"
    weight = 5

[[menu.main]]
    name = "Download"
    url  = "/download"
    weight = 6

[params]
    viewMorePostLink = "/news/"
    author = "DevCows"
    defaultKeywords = ["devows", "hugo", "go"]
    defaultDescription = "Site template made by devcows using hugo"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "/sites/default/files/ReactOS_0.png"
    logo_small = "/sites/default/files/ReactOS_0.png"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = false
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.see_more]
    enable = true
    icon = "fa fa-file-code-o"
    title = "ReactOS is a Free Opensource operating system."
    subtitle = "Imagine running your favorite Windows applications and drivers in an open-source environment you can trust. That's ReactOS. Not just an Open but also a Free operating system."
    link_url = "#"
    link_text = "Click here to learn more"

[params.recent_posts]
    enable = true
    title = "Recent news"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."

[taxonomies]
    author = "author"
    tag = "tags"
